#!/usr/bin/env bash
# =============================================================================
# generate-update-manifest.sh — Tauri Auto-Updater Manifest Generator
# =============================================================================
#
# Purpose:
#   Generates the `latest.json` manifest file required by the Tauri updater
#   plugin to detect and serve updates. This manifest is uploaded to GitHub
#   Releases as a release asset and is fetched by running instances of the
#   app to check for new versions.
#
# Tauri updater flow:
#   1. App starts -> reads updater.endpoints from tauri.conf.json
#   2. Fetches https://github.com/.../releases/latest/download/latest.json
#   3. Compares manifest.version with current app version
#   4. If newer: downloads platform-specific .sig + installer
#   5. Verifies the .sig against updater.pubkey in tauri.conf.json
#   6. Installs and restarts the app
#
# Signing key setup (run ONCE, store outputs as GitHub secrets):
#   npx @tauri-apps/cli signer generate -w ~/.tauri/baduk.key
#   # Outputs:
#   #   ~/.tauri/baduk.key       (TAURI_SIGNING_PRIVATE_KEY secret)
#   #   ~/.tauri/baduk.key.pub   (set as plugins.updater.pubkey in tauri.conf.json)
#
# Required environment variables:
#   APP_VERSION            — Release version, e.g. "1.0.0"
#   TAURI_SIGNING_KEY_PASSWORD — Password for the Tauri signing key
#   GITHUB_REPOSITORY      — "owner/repo", e.g. "YOUR_ORG/baduk-platform"
#
# Optional environment variables:
#   RELEASE_DATE           — ISO 8601 date (default: today)
#   RELEASE_NOTES          — Release notes string (default: see file)
#   OUTPUT_FILE            — Output path (default: outputs/latest.json)
#
# Platform artifact naming conventions (Tauri default):
#   macOS arm64  : Baduk_${VERSION}_aarch64.dmg + .sig
#   macOS x86_64 : Baduk_${VERSION}_x64.dmg + .sig
#   Windows x64  : Baduk_${VERSION}_x64_en-US.msi.zip + .sig
#   Linux x64    : Baduk_${VERSION}_amd64.AppImage.tar.gz + .sig
#
# Usage:
#   APP_VERSION=1.0.0 \
#   GITHUB_REPOSITORY=YOUR_ORG/baduk-platform \
#   bash scripts/generate-update-manifest.sh
#
# Idempotency:
#   Safe to re-run. Overwrites the output file.
# =============================================================================

set -euo pipefail

# ── 1. Validate environment ───────────────────────────────────────────────────

: "${APP_VERSION:?ERROR: APP_VERSION must be set (e.g. 1.0.0)}"
: "${GITHUB_REPOSITORY:?ERROR: GITHUB_REPOSITORY must be set (e.g. YOUR_ORG/baduk-platform)}"

RELEASE_DATE="${RELEASE_DATE:-$(date -u +%Y-%m-%dT%H:%M:%SZ)}"
OUTPUT_FILE="${OUTPUT_FILE:-outputs/latest.json}"

# Build the base download URL for this release
BASE_URL="https://github.com/${GITHUB_REPOSITORY}/releases/download/v${APP_VERSION}"

echo "=== Generating Tauri Update Manifest ==="
echo "  Version    : $APP_VERSION"
echo "  Repository : $GITHUB_REPOSITORY"
echo "  Base URL   : $BASE_URL"
echo "  Output     : $OUTPUT_FILE"

# ── 2. Read .sig files if available ──────────────────────────────────────────
# In a full release pipeline, the .sig files are generated by `tauri build`
# when TAURI_SIGNING_PRIVATE_KEY is set. Here we read them if present,
# and use empty strings as placeholders if not (for manifest structure testing).

read_sig() {
  local sig_file="$1"
  if [[ -f "$sig_file" ]]; then
    cat "$sig_file"
  else
    echo ""
    echo "WARNING: Signature file not found: $sig_file" >&2
    echo "  In CI, this file is generated by 'tauri build' when TAURI_SIGNING_PRIVATE_KEY is set." >&2
  fi
}

BUNDLE_DIR="${BUNDLE_DIR:-src-tauri/target/release/bundle}"

SIG_MACOS_AARCH64=$(read_sig "${BUNDLE_DIR}/dmg/Baduk_${APP_VERSION}_aarch64.dmg.sig" 2>/dev/null || echo "")
SIG_MACOS_X64=$(read_sig "${BUNDLE_DIR}/dmg/Baduk_${APP_VERSION}_x64.dmg.sig" 2>/dev/null || echo "")
SIG_WINDOWS_X64=$(read_sig "${BUNDLE_DIR}/msi/Baduk_${APP_VERSION}_x64_en-US.msi.zip.sig" 2>/dev/null || echo "")
SIG_LINUX_X64=$(read_sig "${BUNDLE_DIR}/appimage/Baduk_${APP_VERSION}_amd64.AppImage.tar.gz.sig" 2>/dev/null || echo "")

# ── 3. Collect release notes ──────────────────────────────────────────────────

RELEASE_NOTES="${RELEASE_NOTES:-Release v${APP_VERSION}. See full changelog at https://github.com/${GITHUB_REPOSITORY}/releases/tag/v${APP_VERSION}}"

# ── 4. Generate the manifest ──────────────────────────────────────────────────

mkdir -p "$(dirname "$OUTPUT_FILE")"

cat > "$OUTPUT_FILE" << MANIFEST
{
  "version": "v${APP_VERSION}",
  "notes": "${RELEASE_NOTES}",
  "pub_date": "${RELEASE_DATE}",
  "platforms": {
    "darwin-aarch64": {
      "signature": "${SIG_MACOS_AARCH64}",
      "url": "${BASE_URL}/Baduk_${APP_VERSION}_aarch64.dmg"
    },
    "darwin-x86_64": {
      "signature": "${SIG_MACOS_X64}",
      "url": "${BASE_URL}/Baduk_${APP_VERSION}_x64.dmg"
    },
    "windows-x86_64": {
      "signature": "${SIG_WINDOWS_X64}",
      "url": "${BASE_URL}/Baduk_${APP_VERSION}_x64_en-US.msi.zip"
    },
    "linux-x86_64": {
      "signature": "${SIG_LINUX_X64}",
      "url": "${BASE_URL}/Baduk_${APP_VERSION}_amd64.AppImage.tar.gz"
    }
  }
}
MANIFEST

echo ""
echo "Manifest written to: $OUTPUT_FILE"
cat "$OUTPUT_FILE"

# ── 5. Validate the manifest JSON ─────────────────────────────────────────────

echo ""
echo "--- Validating manifest JSON ---"

if command -v python3 >/dev/null 2>&1; then
  python3 -c "
import json, sys
with open('${OUTPUT_FILE}') as f:
    manifest = json.load(f)

required_fields = ['version', 'notes', 'pub_date', 'platforms']
for field in required_fields:
    assert field in manifest, f'Missing field: {field}'

platforms = manifest['platforms']
required_platforms = ['darwin-aarch64', 'darwin-x86_64', 'windows-x86_64', 'linux-x86_64']
for platform in required_platforms:
    assert platform in platforms, f'Missing platform: {platform}'
    entry = platforms[platform]
    assert 'url' in entry, f'Missing url for {platform}'
    assert 'signature' in entry, f'Missing signature for {platform}'
    assert entry['url'].startswith('https://github.com/'), f'Invalid URL scheme for {platform}'

print('Manifest validation: PASSED')
print(f'  Version: {manifest[\"version\"]}')
print(f'  Platforms: {list(platforms.keys())}')
"
else
  echo "python3 not available — skipping JSON validation."
fi

# ── 6. Signing key setup documentation ───────────────────────────────────────

echo ""
echo "=== Signing Key Setup Documentation ==="
echo ""
echo "To generate a new Tauri signing key pair (run ONCE per project):"
echo "  npx @tauri-apps/cli signer generate -w ~/.tauri/baduk.key"
echo ""
echo "This produces:"
echo "  ~/.tauri/baduk.key     -> Store as GitHub secret: TAURI_SIGNING_PRIVATE_KEY"
echo "  ~/.tauri/baduk.key.pub -> Copy into tauri.conf.json plugins.updater.pubkey"
echo ""
echo "GitHub Actions usage:"
echo "  env:"
echo "    TAURI_SIGNING_PRIVATE_KEY: \${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}"
echo "    TAURI_SIGNING_PRIVATE_KEY_PASSWORD: \${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}"
echo ""
echo "The Tauri CLI reads these env vars automatically during 'tauri build'."
echo "Each platform artifact gets a .sig file placed alongside the installer."
echo ""
echo "=== generate-update-manifest.sh COMPLETE ==="
